### PR TITLE
Add integration using data-eng circleci context

### PR DESCRIPTION
**Pull request by acmiyaguchi**

### CODE REVIEW

**Comment by acmiyaguchi** [comment]
I followed https://circleci.com/docs/2.0/contexts/ and checked https://github.com/mozilla/bigquery-etl/blob/80d77951ad1dd7024fc3e0f2b1228946d188ac92/.circleci/config.yml#L73-L74, but this fails with `Could not find context "data-eng-circleci-tests"`.

**Comment by jklukas** [comment]
> I followed https://circleci.com/docs/2.0/contexts/ and checked https://github.com/mozilla/bigquery-etl/blob/80d77951ad1dd7024fc3e0f2b1228946d188ac92/.circleci/config.yml#L73-L74, but this fails with `Could not find context "data-eng-circleci-tests"`.

I think that's because this repo is in the mozilla-services org rather than mozilla. I believe contexts are organization-specific.

**Comment by acmiyaguchi** [comment]
This is odd, because based on [bug 1616439](https://bugzilla.mozilla.org/show_bug.cgi?id=1616439), it looks like this context should be available to `mozilla-services`. I've reopened the bug to see if access to this context can be made available to this repository (and to `mozilla-pipeline-schema` as a side-effect).

**Comment by acmiyaguchi** [comment]
Going to close this as a wont-fix type of deal.

**Pull request closed without merging**
