### PR TITLE
Bug 1604910 - Update integration report to use BigQuery document sample

### PR DESCRIPTION
**Pull request by acmiyaguchi**
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1604910)

The integration testing workflow has been modified so it works with the document sample in Bigquery (`moz-fx-data-shared-prod:monitoring.document_sample_nonprod_v1`). 

This is not compatible with the previous `resource/data` folder structure. Instead of `resource/data/<submission_date>/<namespace>/<type>.<version>.batch.json`, this has been flattened into a single folder with the convention `resource/data/<submission_date>/<namespace>.<type>.<version>.ndjson`. It is easier to navigate at a glance.

This also removes `pipenv` as the method for managing the environment. I recommend manually managing the virtual environment using the built-in `venv` module. I move the `Pipfile` file into a `requirements.txt`.

The `sync.sh` script still exists, although it should be in a state to refactor into a python module. Currently the `sync` portion of the script looks like this:

image
[source](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbmludGVncmF0ZVtiaW4vaW50ZWdyYXRlLnB5IHN5bmNdXG5zeW5jW2Jpbi9zeW5jLnNoXVxuZG93bmxvYWRbYmluL2Rvd25sb2FkLWRvY3VtZW50LXNhbXBsZS5weV1cbmdpdChyc3luYyBtb3ppbGxhLXBpcGVsaW5lLXNjaGVtYXMpXG5cbmludGVncmF0ZSAtLT4gc3luY1xuc3luYyAtLT4gZG93bmxvYWRcbnN5bmMgLS0-Z2l0XG5cbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)

I've tested that this works.

```bash
# with my sandbox account
export GOOGLE_APPLICATION_CREDENTIALS=</path/to/credentials.json>

# set up environment
source venv/bin/activate

# run unit tests
make test

# run integration tests
./integration.py sync report
./integration.py compare master master

# run unit and integration tests in docker
make build
bin/docker_env.sh test
bin/docker_env.sh compare master master
```

This works well enough to catch a bug with a recent schema:

```json
...
        "telemetry.crash.4": {
            "error_count": 151,
            "error_rate": 15.1,
            "errors": {
                "Validation Error: ('type', '#/properties/payload/properties/minidumpSha256Hash', '#/payload/minidumpSha256Hash')": 151
            },
            "time": 0.77,
            "total": 1000
        },
...
```

---

I've also set up a sandbox project for this repository under `dataops/sandbox/edge-validator-ci` and created a service account with BigQuery viewer access. There is still uncertainty about the mechanism for authorized views, so the job results in the following error:

```
Traceback (most recent call last):
  File "bin/download-document-sample.py", line 111, in <module>
    main(parse_arguments())
  File "bin/download-document-sample.py", line 98, in main
    write_samples(args.output_path, most_recent_date(), extract_samples())
  File "bin/download-document-sample.py", line 76, in most_recent_date
    return next(iter(query_job))["date"].strftime("%Y%m%d")
  File "/Users/amiyaguchi/Work/edge-validator/venv/lib/python3.7/site-packages/google/cloud/bigquery/job.py", line 3256, in __iter__
    return iter(self.result())
  File "/Users/amiyaguchi/Work/edge-validator/venv/lib/python3.7/site-packages/google/cloud/bigquery/job.py", line 3124, in result
    super(QueryJob, self).result(timeout=timeout)
  File "/Users/amiyaguchi/Work/edge-validator/venv/lib/python3.7/site-packages/google/cloud/bigquery/job.py", line 779, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/Users/amiyaguchi/Work/edge-validator/venv/lib/python3.7/site-packages/google/api_core/future/polling.py", line 127, in result
    raise self._exception
google.api_core.exceptions.Forbidden: 403 Access Denied: Table moz-fx-data-shared-prod:monitoring.document_sample_nonprod_v1: User does not have permission to query table moz-fx-data-shared-prod:monitoring.document_sample_nonprod_v1.

(job ID: 1d81c2ec-d5fa-40f0-ae7e-30261133e7f1)

                       -----Query Job SQL Follows-----                       

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:
   2:    SELECT DATE(MAX(submission_timestamp)) as date
   3:    FROM `moz-fx-data-shared-prod`.monitoring.document_sample_nonprod_v1
   4:    
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
```

### CODE REVIEW

**Comment by acmiyaguchi** [comment]
I decided to close https://github.com/mozilla/gcp-ingestion/pull/1042 in favor of incrementally refactoring this repository, because the beam code runs slowly when validating documents.

**Comment by jklukas** [comment]
> the beam code runs slowly when validating documents

Can you give more detail on what results you're seeing for performance of running the Decoder via docker?

**Comment by acmiyaguchi** [comment]
> > the beam code runs slowly when validating documents
> 
> Can you give more detail on what results you're seeing for performance of running the Decoder via docker?

See https://github.com/mozilla/gcp-ingestion/pull/1042#issuecomment-569989028:

> When running within the docker container, the job does not finish within 20 minutes. 

I had to increase the heap size by a considerable amount just for the sink job to run. I saw all allocated cores (6) running for the duration of the job. I didn't run the decoder job using the local runner, but I didn't get much feedback on what was going from the Dataflow UI.

**Comment by acmiyaguchi** [comment]
I'm going to merge this in, despite the failing CI. The CI is failing due to authorization related to the monitoring datasets. This reflects the failing state of the CI in mozilla-pipeline-schemas too.

**Pull request merged**
